server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = /refs/react {
    return 301 /refs/react/;
  }

  location = /refs/vue {
    return 301 /refs/vue/;
  }

  location = /refs/site-nuxt-components {
    return 301 /refs/site-nuxt-components/;
  }

  location /refs/react/ {
    try_files $uri $uri/ /refs/react/index.html;
  }

  location /refs/vue/ {
    try_files $uri $uri/ /refs/vue/index.html;
  }

  location /refs/site-nuxt-components/ {
    try_files $uri $uri/ /refs/site-nuxt-components/index.html;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
