server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = /design-system/react {
    return 301 /design-system/react/;
  }

  location = /design-system/vue {
    return 301 /design-system/vue/;
  }

  location /design-system/react/ {
    try_files $uri $uri/ /design-system/react/index.html;
  }

  location /design-system/vue/ {
    try_files $uri $uri/ /design-system/vue/index.html;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
